### ISSUE TITLE
More free public transport in Sweden

### ISSUE THREAD

**Issue by Ainali** [ls6/trains-ue#1]
The regions Stockholm,Västra Götaland, Kalmar, Blekinge, Kronoberg, Jönköping, Halland and Skåne have free public transport on their buses, trams and subways for anyone with a Ukrainian passport.

Sources: [Stockholm](https://www.regionstockholm.se/verksamhet/kollektivtrafik/nyheter/2022/03/ukrainskt-pass-galler-som-biljett-i-sl-trafiken/), [Västra Götaland](https://sverigesradio.se/artikel/ukrainska-flyktingar-far-aka-gratis-kollektivtrafik-i-vastsverige), [the rest](https://www.dagenssamhalle.se/samhalle-och-valfard/integration-segregation/regioner-later-ukrainska-flyktingar-resa-gratis/).

(I couldn't figure out how to edit the wiki)

**Comment by ls6** [comment]
Thank you @Ainali :)
I added your information in English and Polish and we'll have Ukrainian translation very soon.

P.S. Your idea of opening an issue was excellent. The wiki is not open for editing so we can make sure everything gets translated to all three languages.
